name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  # - pytorch=1.12.1
  # - torchvision=0.13.1
  - tqdm
  # - pip:
  #   - submodules/diff-gaussian-rasterization
  #   - submodules/simple-knn

# pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
# pip install submodules/diff-gaussian-rasterization
# pip install submodules/simple-knn